RandomForestRegressor:
  "default":
    { }
  "random_search":
    { }
  "grid_search":
#      'n_estimators': [ 50, 100, 200, 400 ]
#      'criterion': [ 'friedman_mse', 'squared_error' ]
#      'max_depth': [ 2, 3, 4, 5, 6, 7, 8, 9, 10 ]
#      'min_samples_split': [ 2, 5, 10, 15, 20, 25 ]
#      'min_samples_leaf': [ 2, 4, 6, 8, 10 ]
    { }
  "cv": 5
